### ISSUE TITLE
Cannot transcribe speech to text for model without RNNLM and rescore

### ISSUE THREAD

**Issue by yli223** [alphacep/vosk-unity-asr#4]
Hey, I implement a unity project that uses Vosk. The current model is around 5GB, which performs really well, but it is too large. It takes around 5 seconds to give the answer through Unity. So I remove RNNLM and rescore folders in my model. It works fine when I run it through python, which means the smaller model can give me the expected text based on my speech. But after integrating this model into unity, it cannot recognize the same input speech. I wonder if the model without RNNLM and rescore folders is supported in the unity project? If so, can anyone point me out why the model cannot perform the same as the python project?

**Comment by nshmyrev** [comment]
Removal of rnnlm and rescore should not affect results much, you probably changed some other things in process like data processing. I suggest you to start with a clean state again.
