### ISSUE TITLE
Have "File Not Found" error when vosk receive voices

### ISSUE THREAD

**Issue by Snail921** [alphacep/vosk-unity-asr#5]
[Picture](https://imgur.com/a/2yc8plU)
As you can see, after decompression completed successfully, the editor throws when the vosk receives voices.
The windows running on Japanese system but does it matter? This had never happened with old project which had inevitable crash issue for the first launch.
Can you point out where the source of this issue?

**Comment by nshmyrev** [comment]
Ok, and what is the translation of Japanese message after Win32Exception on the screenshot?

**Comment by Snail921** [comment]
It says "The designated file is not found."

**Comment by nshmyrev** [comment]
It tries to execute TTS espeak I think and fails. See the code. You can change it to some other TTS method.

**Comment by nshmyrev** [comment]
Here:

https://github.com/alphacep/vosk-unity-asr/blob/master/Assets/Scripts/VoskDialogText.cs#L73

**Comment by Snail921** [comment]
Oh I see.
Now I get it working perfectly.
Thanks for the advise.

**Comment by Snail921** [comment]
Oh I see.
Now I get it working perfectly.
Thanks for the advise.
